# ================================================================================
# Variables
# OCIDs are passed in from 01-infrastructure terraform outputs via apply.sh
# ================================================================================

variable "compartment_ocid" {
  description = "OCID of the compartment to deploy resources into"
}

variable "subnet_ocid" {
  description = "OCID of the packer subnet from 01-infrastructure"
}

variable "availability_domain" {
  description = "Availability domain resolved by 01-infrastructure"
}

variable "ssh_public_key" {
  description = "SSH public key generated by 01-infrastructure for instance access"
}

variable "packer_password" {
  description = "Password for the packer OS user on deployed instances"
  sensitive   = true
}

variable "deploy_windows" {
  description = "Set to false to skip deploying the Windows desktop instance"
  type        = bool
  default     = true
}
